import java.util.ArrayList;
import java.util.List;


class Student{
    String name;
    double cgpa;
    int id;
    
    public Student(int id, String name, double cgpa){     
        this.setId(id);
        this.setName(name);
        this.setCGPA(cgpa);
    }
    
    public void setId(int id) throws IllegalArgumentException{
        if (id>=1 && id<=10e5){
            this.id = id;
        } else {
            throw new IllegalArgumentException();
        }
    }

    public int getID(){
        return id;
    }
    
    public void setName(String name) throws IllegalArgumentException{
        if (name.length()>=2 && name.length()<=30){
            this.name = name;
        } else {
            throw new IllegalArgumentException();
        }
    }

    public String getName(){
        return name;
    }
    
    public void setCGPA(double cgpa) throws IllegalArgumentException{
        if (cgpa>=0 && cgpa<=4){
            this.cgpa = cgpa;
        } else {
            throw new IllegalArgumentException();
        }
    }

    public double getCGPA(){
        return cgpa;
    }

}

class Priorities{
    
    public static List<Student> getStudents(List<String> events){
        List<Student> students = new ArrayList<Student>();
        for (String event: events){
            System.err.println(event);
            String[] e = event.split(" ");
            if (e[0].equals("ENTER")){                
                String name = e[1];
                double cgpa = Double.parseDouble(e[2]);
                int id = Integer.parseInt(e[3]);
                Student s = new Student(id, name, cgpa);
                students.add(s);
                students = sortCGPA(students);
            } else if (e[0].equals("SERVED")){
                if (students.size()>0){
                    students.remove(0);     
                } else {
                    System.err.println("EMPTY");
                }
                
            }
        }   
        return students;
    }
    
    private static List<Student> sortCGPA(List<Student> students){
        double max = 0;
        for (Student s : students){
            if (s.cgpa>max){
                max = s.cgpa;
            }
        }
        List<Student> sort = new ArrayList<Student>();
        List<Student> notSort = new ArrayList<Student>();
        for (Student s : students){
            if (s.cgpa==max){
                sort.add(s);
            } else {
                notSort.add(s);
            }
        }
        if (sort.size()>1){
            sort = sortName(sort);
        }
        List<Student> anotherSort = new ArrayList<Student>();
        if (notSort.size()>1){
            anotherSort = sortCGPA(notSort);
        } else {
            anotherSort = notSort;
        }
        List<Student> merge = new ArrayList<Student>();
        merge.addAll(sort);
        merge.addAll(anotherSort);
        return merge;
    }

    private static List<Student> sortName(List<Student> students){
        String min = "z";
        for (Student s : students){
            if (s.name.compareTo(min)<0){
                min = s.name;
            }
        }
        List<Student> sort = new ArrayList<Student>();
        List<Student> notSort = new ArrayList<Student>();
        for (Student s : students){
            if (s.name.equals(min)){
                sort.add(s);
            } else {
                notSort.add(s);
            }
        }
        if (sort.size()==0){
            System.err.println("teste");
        }
        if (sort.size()>1){
            sort = sortId(sort);
        }
        List<Student> anotherSort = new ArrayList<Student>();
        if (notSort.size()>1){
            anotherSort = sortName(notSort);
        } else {
            anotherSort = notSort;
        }
        List<Student> merge = new ArrayList<Student>();
        merge.addAll(sort);
        merge.addAll(anotherSort);
        return merge;
    }

    private static List<Student> sortId(List<Student> students){
        int max = 0;
        for (Student s : students){
            if (s.id>0){
                max = s.id;
            }
        }
        List<Student> sort = new ArrayList<Student>();
        List<Student> notSort = new ArrayList<Student>();
        for (Student s : students){
            if (s.id==max){
                sort.add(s);
            } else {
                notSort.add(s);
            }
        }
        List<Student> anotherSort = new ArrayList<Student>();
        if (notSort.size()>1){
            anotherSort = sortId(notSort);
        } else {
            anotherSort = notSort;
        }
        List<Student> merge = new ArrayList<Student>();
        merge.addAll(sort);
        merge.addAll(anotherSort);
        return merge;
    }

}

public class PriorityQueue {
    
    private final static Priorities priorities = new Priorities();
    
    public static void main(String[] args) {
        System.out.println(System.getProperty("java.version"));
        List<String> events = new ArrayList<>();
        events.add("ENTER enpvkNNsnuTTsnisdDMLUDlzH 2.61 75063");
        events.add("SERVED");
        events.add("ENTER RZQamFzODtqeESj 0.43 6539");
        events.add("SERVED");
        events.add("ENTER MLKGXqffmFOoaKhLA 1.80 4319");
        events.add("ENTER NnqxvtQlKzkADwaKlY 3.17 83081");
        events.add("ENTER PizUeyounCIorWApVq 3.96 79156");
        events.add("SERVED");
        events.add("ENTER TpLDy 3.20 20320");
        events.add("ENTER MVkLXNMNNUKpfkbySNIWR 2.67 63941");
        events.add("ENTER xbtBMfkUHBASEQNGXjdkbs 1.12 2818");
        events.add("SERVED");
        events.add("ENTER PyVnujqOLRazp 3.80 451");
        events.add("SERVED");
        events.add("ENTER dWFvjLUWLkw 2.58 39744");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER DZtJfrcxtVefuhMZNFnUcCGy 2.58 5112");
        events.add("SERVED");
        events.add("ENTER hGjMQ 1.82 23479");
        events.add("ENTER ezHwmbXlpJjHTGciP 1.61 39447");
        events.add("SERVED");
        events.add("ENTER sWIMxLcJLOwQxr 0.83 7335");
        events.add("ENTER eilbUqVAWNfDTvIVNohMQGuz 3.83 83907");
        events.add("ENTER fnhHWqMSeQIbAbtKUHMRlXLez 1.30 47912");
        events.add("ENTER ZToRTPejjznEnlGHhCWuEB 1.79 29407");
        events.add("ENTER hGyHUlvX 3.76 74499");
        events.add("SERVED");
        events.add("ENTER RcupXzlsMaDuvCvllzrnFam 2.27 77746");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER ObEanUXRX 2.59 66631");
        events.add("ENTER hOtbRiNazPVPnHEhvSECd 0.50 33578");
        events.add("ENTER xlFpcsh 3.50 43471");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER EIYpC 3.06 82152");
        events.add("ENTER zqlCQMhVQoFESKFMazhoqv 0.69 96877");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER gCUsSncIWkGymhundzSR 1.04 83653");
        events.add("ENTER vOZNtJIP 1.39 93955");
        events.add("ENTER FCLoPEOEfxQmWUZMibkNcUG 3.19 93317");
        events.add("ENTER zwzKIBiPq 2.52 53386");
        events.add("SERVED");
        events.add("ENTER pseZjMcGBsUnwh 2.47 70619");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER dWHdCSJMh 3.38 88867");
        events.add("ENTER cWRotLfbkwQlXgY 1.81 36410");
        events.add("ENTER fwYVXyRfyNBHb 1.35 1794");
        events.add("ENTER oZgOaKzgQ 2.49 92131");
        events.add("ENTER duRMvjkEcXgMFSmTNA 0.76 71763");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER boPjffcHWpgAltCt 2.03 46985");
        events.add("ENTER fyOudghwwjFtNiunTdkfqmQ 2.87 78058");
        events.add("ENTER CGWAEDIXezM 2.83 43639");
        events.add("ENTER uLDYfTYSWlChkY 0.26 96408");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER ssIGabFYZZGJQgxB 0.41 67877");
        events.add("ENTER tzZQrSusAufJzTXKqFJVwEWVe 0.69 55353");
        events.add("ENTER OSWDlgFMdYyIYYFmOpwgvTSHf 3.57 13615");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER ZXoXsKRIfTtH 2.10 15320");
        events.add("SERVED");
        events.add("ENTER LICiHdDYHpoQc 0.08 40165");
        events.add("ENTER wKscQoTSvmsuTyLbpXWKG 3.05 26818");
        events.add("ENTER WtTUqhxzkleCUMaBJrOwiFrPm 2.23 79880");
        events.add("ENTER qPhflUQDnVvjuksEek 3.52 40269");
        events.add("ENTER WnVOiSjPEtKATnbkmFs 1.23 74671");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER SUTEufdzLUiGtVuNibZKJW 3.95 39822");
        events.add("SERVED");
        events.add("ENTER KeBOhPOsP 0.17 43886");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER UhJmcESatAPCcGPC 3.66 4287");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER aAqoVe 1.73 24072");
        events.add("ENTER qJCRKggwoHHRVeYUcrbrvwG 0.50 52602");
        events.add("SERVED");
        events.add("ENTER CcHzSIcuGJPyBaatK 3.34 43795");
        events.add("ENTER wsgyosEzBIvCZ 0.09 6749");
        events.add("ENTER YXvMRcn 0.18 20631");
        events.add("ENTER lkWuxgRCCsiMDyHQC 2.37 39726");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER AQIvPOuVfxDAXBhtTKyhigli 2.25 66058");
        events.add("SERVED");
        events.add("ENTER WjcFbBxqzOvccj 2.25 12334");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER dLdNyaCsuRRPGK 0.31 29745");
        events.add("ENTER DJDwVzbWiDIie 2.79 93811");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER svoKgXvhApggnIHadk 1.50 33537");
        events.add("ENTER QKsygdpG 0.34 85260");
        events.add("SERVED");
        events.add("ENTER JSHoYFdSodxkBkfscU 2.91 34623");
        events.add("ENTER HddoTfvesEDJPFFtIdnJsXolF 0.44 27806");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER EUvVsFNXRObJa 1.29 16641");
        events.add("ENTER TRmynwVwkLmVyOp 2.72 98636");
        events.add("ENTER inAtYevFDiDCnueu 1.03 54812");
        events.add("ENTER JBemYz 0.24 63605");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER XfilZygKZ 2.44 87029");
        events.add("ENTER ZPpkgUx 2.37 74383");
        events.add("SERVED");
        events.add("ENTER PLOGjasZCmKXQQSDfyMx 0.81 59324");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER mcRNyYVtljziCqprCi 3.48 15953");
        events.add("SERVED");
        events.add("ENTER FAgHzYuYaLTlSxvUOfx 2.76 20758");
        events.add("ENTER qYRwaHrpVp 2.55 37879");
        events.add("SERVED");
        events.add("ENTER vbbHJOLN 1.61 69760");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER LYUeMJCbXumsODxEFu 2.49 40625");
        events.add("ENTER xwmlxw 2.80 35393");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER HqYPNBLcLeEUKcqmOXcekVIgQ 3.48 87489");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER WkpPqDuPuRQi 1.63 78543");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER SxDBBsgBDeB 0.42 31775");
        events.add("ENTER MZDewLOpldEHyedi 3.02 20755");
        events.add("ENTER DQVKNNixIiSpIN 3.40 24648");
        events.add("SERVED");
        events.add("ENTER QGVFRInaFqiEyZW 0.36 88446");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER eVirc 2.52 17098");
        events.add("SERVED");
        events.add("ENTER MtdtaURVlWw 3.61 78554");
        events.add("ENTER LBQhqWBAnPf 1.07 99639");
        events.add("ENTER XPohLrPdQQSB 1.83 13939");
        events.add("ENTER vNitEzFkgdyGujAwn 2.50 81663");
        events.add("SERVED");
        events.add("ENTER CKYnjLhxRuQgHHIabFkarU 2.46 98923");
        events.add("SERVED");
        events.add("ENTER jcmQwGEWRrAfOFoU 3.52 38432");
        events.add("SERVED");
        events.add("ENTER DbpSvpXbKgqtgtLKzfLBtPlL 3.67 6456");
        events.add("SERVED");
        events.add("ENTER pfextlVogyzTPlXAdIKPNpYI 1.20 84985");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER oyMplSbYGKT 3.24 90312");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER mLrcOvf 1.57 12924");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER sHatqYnyheprkMQvqO 3.55 77926");
        events.add("ENTER NsfTlhwJLHoJIxzld 0.80 95388");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER uXCNsSjVQMNHayvOVVpfBizVD 3.02 87223");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER XNGUsVY 1.92 69778");
        events.add("SERVED");
        events.add("ENTER Esmurhj 0.54 70239");
        events.add("SERVED");
        events.add("ENTER QIkLyFCle 1.06 61613");
        events.add("ENTER SBCbXaJnCaZJrWykQbDtkubc 3.34 53170");
        events.add("SERVED");
        events.add("ENTER rpCdh 0.29 51778");
        events.add("SERVED");
        events.add("ENTER EUJWIqBDdnzEcpYbHKKBOFihw 3.24 85595");
        events.add("ENTER pQUoZSWpdS 3.28 55242");
        events.add("SERVED");
        events.add("ENTER FXhwpoOD 2.91 48577");
        events.add("ENTER IeSHY 1.20 66939");
        events.add("SERVED");
        events.add("ENTER TnAAcRnBuGVKCnFxgYOCc 3.76 95527");
        events.add("SERVED");
        events.add("ENTER pdqPgwBMSpufigfSthedePIrC 3.11 50911");
        events.add("SERVED");
        events.add("ENTER IuUnEIoUdzqYLopzfWDXqOstt 1.31 22230");
        events.add("ENTER xxszoHRKR 1.66 3494");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER FflPgrmzBbkHalMrGTG 2.78 34377");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER LleqtUrGxtcnUXxlpa 2.47 49987");
        events.add("ENTER CBhrQCAvIVnzGJ 1.73 97770");
        events.add("SERVED");
        events.add("ENTER JUddSKSzF 0.96 87832");
        events.add("SERVED");
        events.add("ENTER dKbFTVOYbnYgZbuwPk 1.75 27263");
        events.add("SERVED");
        events.add("ENTER aPiynmj 0.15 1613");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER SSzVeXyGGQjIEGXFnBlAbL 3.74 82393");
        events.add("SERVED");
        events.add("ENTER njHsiFGCbPJEelqKWOyUKRGyl 1.93 47787");
        events.add("ENTER vkUzqBRCfY 1.05 95664");
        events.add("ENTER NHooMPRMMZP 2.19 55610");
        events.add("ENTER yyoWVb 3.55 35610");
        events.add("ENTER CHHfZgZhCASWTNeUC 0.89 95021");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER gOZDUBkOlXOCKOvMuC 1.68 80467");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER nDaxxjnBMdP 0.77 14730");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER BIlTySoZqtdLD 2.96 97349");
        events.add("ENTER CCmkrWU 0.49 47083");
        events.add("ENTER ioyjVdCX 2.73 48669");
        events.add("ENTER WHHPZcxyvNQBIVGyMazt 2.84 56117");
        events.add("SERVED");
        events.add("ENTER zfehWF 1.32 35364");
        events.add("SERVED");
        events.add("ENTER tcQBMil 0.49 54541");
        events.add("SERVED");
        events.add("ENTER saBihapFUtHFecIHt 3.53 42957");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER aJOEvGrUHIi 3.66 36545");
        events.add("ENTER azUWDrw 0.13 15842");
        events.add("ENTER toKTBOqmqETzBUDG 3.57 18043");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER RkBsuTaBJrcKXeBqjUc 2.01 16378");
        events.add("ENTER NsMQF 2.09 4953");
        events.add("ENTER UGxWvWPpvouZ 2.85 4159");
        events.add("ENTER jqqfldAaZFulDrEEuHfL 3.78 56454");
        events.add("SERVED");
        events.add("ENTER ZUoHiQfuMxAevNXJuuZTiPYZP 3.41 9561");
        events.add("ENTER VRIAYwZlSOqdMWjPyzyLO 2.54 41733");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER emWNHtPX 2.62 33068");
        events.add("ENTER BUsbv 0.66 78953");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER ANSOPSP 2.49 25609");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER xnfeYzLbWFNj 0.28 90654");
        events.add("ENTER usWerCpxTgmDXrzE 0.94 86763");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER fwZEDFbRRsyLoviAUJ 0.53 54879");
        events.add("SERVED");
        events.add("ENTER VbqWTBycnLTOiCAKkRnmYyVn 0.56 83504");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER muDPuRdE 1.90 49830");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER FOWID 0.96 85995");
        events.add("ENTER LBFVxysgEbLnOuWHJjIpGEI 1.54 48406");
        events.add("ENTER kguGWFOp 3.98 83784");
        events.add("ENTER TwmGLifSnPREct 2.92 94602");
        events.add("ENTER ipJJcbUVg 1.83 82995");
        events.add("SERVED");
        events.add("ENTER UiYLKemAtT 2.54 75422");
        events.add("SERVED");
        events.add("ENTER fsEboqxcwJaNOo 3.68 10798");
        events.add("ENTER uxFiygjmCtFBCScaYll 3.37 25694");
        events.add("ENTER aeTOTDAgQJiYyNGlt 0.98 93036");
        events.add("ENTER zVumptt 2.67 87482");
        events.add("ENTER GdYQFpdD 0.66 28275");
        events.add("ENTER sdUyNlNFQqRLF 1.47 64674");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER zRorCcHICceAgVeamyag 1.34 49704");
        events.add("SERVED");
        events.add("ENTER ENYSSYciWAigUxKWGCegBBP 1.37 40942");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER raWruzwDkLJrT 3.06 87044");
        events.add("ENTER EbgyLMcWGkP 0.45 78086");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER bepstlbCgiNLfMwcCL 0.69 99613");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER tWGNKjhNTdpTWhTnvpAIqFEK 3.61 92968");
        events.add("SERVED");
        events.add("ENTER hZkpsYilckzLkWktCp 1.30 36613");
        events.add("ENTER tQKVeQBsdjALVYlAnUin 1.86 34154");
        events.add("ENTER zdaXLHQoZU 0.11 36577");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER cEbxhHnHcQtKfqKLjPh 3.56 98265");
        events.add("SERVED");
        events.add("ENTER UphJdguGxBNGhZ 3.11 28360");
        events.add("ENTER AesnbubQXST 2.42 40236");
        events.add("SERVED");
        events.add("ENTER ZcBqIWLivF 2.86 93404");
        events.add("ENTER aKwxh 3.24 48922");
        events.add("ENTER xPorPztEaoOEPuMqN 0.10 84764");
        events.add("ENTER tzLtcyuELbeKFVN 3.98 35450");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER sksnxOdqmfDtjzfXXG 1.84 87812");
        events.add("ENTER HebumZJvsplOAWOBHGn 0.18 77749");
        events.add("SERVED");
        events.add("ENTER mFJuUsigFhmFVLsUAGZ 3.31 49999");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER eKLVTZRoncgUngGqDEejbsLD 0.68 65157");
        events.add("ENTER wssBzoDlKlvTWFnDie 3.37 7304");
        events.add("ENTER BXvMMApfuzjsYYT 0.69 62814");
        events.add("ENTER fIcaKfZYSmpIgQMEQbau 1.83 57152");
        events.add("ENTER QTKqAgivtdEgPGbY 3.48 27287");
        events.add("ENTER LPdvjUEbzhhRkxecKDvn 3.58 6180");
        events.add("ENTER gBbNfGatFqhZyO 3.53 60388");
        events.add("ENTER BeRKayKjM 3.21 25884");
        events.add("SERVED");
        events.add("ENTER PbDgXwUxAFGd 3.24 57221");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER BZsBgXTzPnprGZcJFjQgYvh 1.49 83855");
        events.add("ENTER WZnrBUb 2.93 73155");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER EPkKCQavKOf 1.08 94156");
        events.add("SERVED");
        events.add("ENTER HxHkXGSDWFOxE 3.70 10296");
        events.add("ENTER hVLwDWgPIIGfiGlk 0.62 6807");
        events.add("ENTER waZxcqgDMGZLAP 1.44 36300");
        events.add("ENTER KqnrMWzgBYCkD 0.37 10517");
        events.add("SERVED");
        events.add("ENTER yMKdNjStWNewLLoAiIntWm 2.10 48270");
        events.add("SERVED");
        events.add("ENTER FXSNwZVexHlEiSQqsvm 1.30 2193");
        events.add("SERVED");
        events.add("ENTER dGmfwgnyOyWnzJuetM 3.45 43043");
        events.add("SERVED");
        events.add("ENTER gynpaa 2.42 82340");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER uimloeFyW 0.42 2403");
        events.add("ENTER lVNaA 0.37 24219");
        events.add("ENTER VicuXRakCzq 3.10 65775");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER GGegrmodyyfQaEIokBN 3.46 97995");
        events.add("ENTER YodKsvKhKqjDTM 0.62 97849");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER VrfIQxcKtYYL 2.97 2635");
        events.add("ENTER dQSENQdXzthwXXnrcpEPUgFGP 1.53 10487");
        events.add("ENTER YUHhvpoOZPWND 2.90 13318");
        events.add("ENTER FcOaiBgaAErKw 2.29 52470");
        events.add("ENTER RuqEdGHUUpSTFi 2.03 53781");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER hryqZXQKuNjYmbomC 2.44 6893");
        events.add("SERVED");
        events.add("ENTER JdzkKKnTMICoBoRmyVeCuU 2.69 29192");
        events.add("ENTER lVClkNHPTbdWhsXJqyRXlde 2.42 92725");
        events.add("SERVED");
        events.add("ENTER QoYQrHCejWyNAG 1.12 88478");
        events.add("ENTER kEtvBJHCE 0.93 60411");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER LrdMFTiGjHNvGqP 2.98 65284");
        events.add("SERVED");
        events.add("ENTER aykHltBrkhJlJRaaT 1.25 20408");
        events.add("ENTER NFgqyFAwkSo 2.99 6841");
        events.add("ENTER IavLMJOteBazvZHTzPCy 2.86 96983");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER GaDeYopcynsmBIHWokzSOxJJ 0.06 12485");
        events.add("SERVED");
        events.add("ENTER AYOKmUtcqQL 0.84 52736");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER ttheStBHikCeYDpTiDbAwEgwK 1.57 36113");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER jCNReQCq 2.66 86624");
        events.add("ENTER OSdyziFUqjeLaOYaxzsoPvg 1.11 53716");
        events.add("SERVED");
        events.add("ENTER PyWMfSwGVPnFIhwbFRDRPFXy 2.43 45000");
        events.add("ENTER YxJzCoU 1.07 80057");
        events.add("ENTER rfiPDeevIjitrwRG 1.22 4615");
        events.add("ENTER RiCHJ 0.52 37096");
        events.add("ENTER jAwxSDp 2.32 83001");
        events.add("SERVED");
        events.add("ENTER hoTiaJLCXGGl 3.10 7867");
        events.add("ENTER DaAdcmiYckDtdmCRSyrDWATGh 2.62 53360");
        events.add("ENTER oQIDNklyxoJZSbRML 0.47 97765");
        events.add("ENTER wVlxpJrWXuKRaMzHOrIBUwXgm 3.18 12382");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER uWrXFWK 1.90 76139");
        events.add("ENTER TviYGjCDgTqotTNwYwz 2.60 13241");
        events.add("SERVED");
        events.add("ENTER yQRRZXvVVpo 3.85 75106");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER KVwgDIXSoUecJsOBtRNvftN 2.76 17973");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER mCjRyf 3.43 62863");
        events.add("ENTER lKuSWErCGbQqpyV 2.35 39494");
        events.add("ENTER AmgHXWMGfVSaXQqngyk 0.38 32882");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER xFbwyPNau 2.39 93917");
        events.add("ENTER rmihrCtMnqRjm 1.28 56930");
        events.add("ENTER NVQDWTyMQm 1.21 91079");
        events.add("ENTER ZIXJPagPvhCPa 0.86 45561");
        events.add("SERVED");
        events.add("ENTER fVXsJSWfkLrAB 2.45 61695");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER fkJYJJEqpxO 3.59 52068");
        events.add("ENTER BEcXqlwLK 3.32 39470");
        events.add("ENTER XGMVOfpbpVYsRQMXCyaDZE 3.94 18696");
        events.add("ENTER ckwNVsecdPvDHFejoSluKSk 2.37 78808");
        events.add("ENTER TCxDKXLazoTsVzUjIZw 1.15 98308");
        events.add("ENTER WeGEIP 0.55 60460");
        events.add("ENTER kjhVDFNLMfLyBsQuSQZL 1.48 53930");
        events.add("SERVED");
        events.add("ENTER SSQJXtLCzsCdRyYJkfwgwDQR 2.47 47010");
        events.add("ENTER AEaNNqOJHNuwQXxtpPJIICKK 0.26 15864");
        events.add("ENTER yODVFVnUGIFXIQpvhiSXgnnZS 1.07 60486");
        events.add("ENTER UyiOLHvwwzrZrJirJtlgpAOut 1.27 465");
        events.add("SERVED");
        events.add("ENTER uGNTgV 0.46 66214");
        events.add("ENTER KOAIBCCoyWLaqiOYe 2.51 990");
        events.add("SERVED");
        events.add("ENTER kilarbmJegiacmyLMoT 2.14 49626");
        events.add("ENTER ofRMgVrDTKBzlUvKVLwaqX 2.61 31052");
        events.add("ENTER mKwuNVUMyeL 2.75 27632");
        events.add("ENTER FBGyqeYXdrnkQahjDVZjO 0.46 31053");
        events.add("SERVED");
        events.add("ENTER EaBLhE 1.42 37618");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER lAXvhYkfvpnOYsbkMPfmK 2.02 81190");
        events.add("SERVED");
        events.add("ENTER HLVFkCxTPJZF 1.20 6979");
        events.add("SERVED");
        events.add("ENTER CtRTCmNazZRMsHssflkk 0.36 10348");
        events.add("ENTER LrvJjPfMduXyFou 0.82 16447");
        events.add("ENTER opsJzGtQTndH 3.45 75605");
        events.add("ENTER tDaRpDy 0.90 43073");
        events.add("SERVED");
        events.add("ENTER xBaKzGvyKp 3.10 55831");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER hjGJxRWa 3.84 66558");
        events.add("SERVED");
        events.add("ENTER QnAPWE 1.87 67187");
        events.add("SERVED");
        events.add("ENTER xrnDbEJDQbasuQINHejyGaNCV 3.15 48658");
        events.add("ENTER cphbPklCHIXys 2.63 27734");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER ssBzyGRJ 3.91 38891");
        events.add("ENTER uNEKBwRmsYqewFFgi 2.21 7479");
        events.add("ENTER VJokndOMQjZ 2.74 19574");
        events.add("SERVED");
        events.add("ENTER NOcRnJToi 2.87 25728");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER nZraCOhMSjb 2.49 75054");
        events.add("ENTER ZRHPmznLrRweoE 0.36 36897");
        events.add("SERVED");
        events.add("ENTER BtjYbjdJNp 2.76 87732");
        events.add("ENTER rIxCwsQmWjJgUgL 0.87 71666");
        events.add("SERVED");
        events.add("ENTER FcTmZpeYBDqrEDnjDGpq 2.92 46697");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER eWEftITpyFh 1.62 3987");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER xiBwrtEHdMoRI 0.41 41376");
        events.add("ENTER YBtehn 0.25 76168");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER lbQUgdmTZrs 3.70 27356");
        events.add("ENTER pKsXVhRFMeNnewjnKiOuif 1.44 72367");
        events.add("ENTER SUOcNhMzPxMpDvABDlU 1.93 41174");
        events.add("ENTER OIdsO 0.13 33145");
        events.add("SERVED");
        events.add("ENTER bKHNigtfXzaQlcBEXtzXbovgK 1.72 99764");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER AbMtMYIpAbVu 2.44 72640");
        events.add("ENTER mRCtCDAVvZIdylfJEfmcqFK 1.52 18327");
        events.add("ENTER lmoTwBEpO 0.21 58787");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER TiPTdksEU 0.85 9680");
        events.add("ENTER gujnJeVgOTEBdsxp 0.51 17764");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER HfcClJMMNMVyFNql 3.13 1065");
        events.add("ENTER DBNFBbbXSbGDlZDOgGwn 1.21 89080");
        events.add("ENTER EcTakauxNNEmuExXUbFdk 3.83 20250");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER vqZZgNVXNSzlMEKxAjaoxPpB 1.93 7444");
        events.add("SERVED");
        events.add("ENTER IXoznt 3.93 80962");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER hvZDIYeeASJhNSpKVhkjbAD 3.46 84661");
        events.add("ENTER koGKAMIAWNNpeEwjaHMA 1.92 32802");
        events.add("ENTER hqIiEtMeqfNopyJL 0.31 54602");
        events.add("ENTER MhZTKBuGsWuMb 0.66 6165");
        events.add("SERVED");
        events.add("ENTER SuJbqSFOCbDPvqxMtlMN 1.82 70695");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER xJcYFfXzMKRPIrxjAip 1.43 48186");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER TlMSlCoGj 1.33 63654");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER HHYJCrDHjNTKsoTuH 0.70 9970");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER yYazIcndwuCPPXuXp 0.42 61012");
        events.add("ENTER UDpZwNUVqZRPfzWYiMgyKTxBh 3.97 47782");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER GCIukgDhpQf 2.37 60719");
        events.add("ENTER lWBjimkVcmAoJhsuCbx 2.02 91381");
        events.add("ENTER KQYVaUrNSiDXittiESGxJe 0.65 27629");
        events.add("SERVED");
        events.add("ENTER vRPTaC 2.79 886");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER QPcYZZkYepZBwjLFshZoXMV 1.47 56533");
        events.add("ENTER HBeamAFcflPtBXFy 2.35 15089");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER WcFJJTbfMzsLh 1.45 64162");
        events.add("SERVED");
        events.add("ENTER GfdYm 2.56 40036");
        events.add("ENTER pFDgFbOuQSiMxol 0.18 42485");
        events.add("SERVED");
        events.add("ENTER kHEhTxuPhqFSMjeOC 2.28 4404");
        events.add("SERVED");
        events.add("ENTER cXZdZtaGVTo 3.31 2356");
        events.add("ENTER StOdKWqRUdtUfZBMGHXjPqyE 3.78 36904");
        events.add("SERVED");
        events.add("ENTER SstQEaBIwcG 2.64 54755");
        events.add("ENTER DPmYOHanwK 3.41 52437");
        events.add("ENTER RFjXJSGPKQzWOyUN 3.57 83530");
        events.add("ENTER mtQaNsqoXhjuQXZFmhg 2.36 73240");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER hgVogohSgqUuKr 0.91 93548");
        events.add("ENTER HseRHswUNzHHJxQDZciGmVCzE 2.32 9273");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER UtbVVKHAPUhczlMYvJzznFCVF 0.43 92121");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER etAOrNbUFzV 1.11 22078");
        events.add("ENTER PKBNCUv 1.27 14719");
        events.add("ENTER MJkbsOToDEuPXGcxaqh 0.21 92163");
        events.add("ENTER KllGxvTYBDurvyg 1.03 36380");
        events.add("ENTER eGLtBK 1.12 20774");
        events.add("SERVED");
        events.add("ENTER gWkKkfDogootzYtfyO 2.27 79165");
        events.add("SERVED");
        events.add("ENTER DdytxekvUq 0.10 20687");
        events.add("ENTER scsOdsfnmrRlEBtUQtLW 1.87 81881");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER XGBUDuRnWDdMynej 3.41 43717");
        events.add("SERVED");
        events.add("ENTER DCmbWpxWbCjBPP 3.91 98438");
        events.add("ENTER tCjCABBMz 3.42 14420");
        events.add("ENTER USWucFepiyUogSqajJqtIZ 3.62 14460");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER QRCNiXoMBDdBhM 2.85 90142");
        events.add("ENTER MwPLcNfdICmveIsSILFaQjKre 2.21 85631");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER EoNwxiXEzAwW 1.19 47716");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER OxSCDKKSyIp 2.30 57396");
        events.add("ENTER JcAbMVNSEA 1.07 29282");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER gfhWSLQvfioUtDpOeDMNEHFt 2.74 20470");
        events.add("SERVED");
        events.add("ENTER NtWdAPTLypXEwcvxY 3.06 3284");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER QDXyRFyrAyZoDjIiOKAQCi 3.58 56050");
        events.add("SERVED");
        events.add("ENTER CtNhRdsZhIOazxxWKm 0.89 74576");
        events.add("ENTER CrfgDhoAeqSLNotOPkBrjVfpx 1.73 53364");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER PDQwVrJRp 3.41 44081");
        events.add("ENTER GNbZOBRHKviZZJyMq 1.78 47967");
        events.add("ENTER fRPjqtrHEINrFEDWYPiagKT 3.04 73461");
        events.add("ENTER HnbsgAfmegn 1.24 99316");
        events.add("SERVED");
        events.add("ENTER SskOVVZNzCaMC 3.23 40291");
        events.add("ENTER ERTYTgdF 1.73 59163");
        events.add("ENTER KzRADbmbhBFqnhdjOoSd 0.90 8638");
        events.add("SERVED");
        events.add("ENTER XKpSCcyeUMrdj 3.14 98885");
        events.add("ENTER nLvZjBydLOCXkXaZa 2.07 87671");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER SFdpiyOVicyCiJhvQ 3.45 27866");
        events.add("ENTER JsFbvG 3.19 20038");
        events.add("SERVED");
        events.add("ENTER YCBaFsUWpDJFFaJgtKS 2.47 73326");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER elKJhvP 1.95 22200");
        events.add("ENTER BGODrpgheNuILfUhWSslWTKM 1.91 8985");
        events.add("ENTER fvfKYA 2.52 22764");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER JlyDFbfjSomYGOizhjhKmBXJ 2.04 20303");
        events.add("ENTER XEQdxJ 1.91 94140");
        events.add("ENTER iygawWnfFCM 0.52 97789");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER aVidElJPiFPOjZaj 0.26 37800");
        events.add("ENTER MPUFSeXOnRUONciPjJdXHi 0.31 38446");
        events.add("ENTER CkjAepPwMdsKwmYxHX 0.96 73058");
        events.add("ENTER rJvbgxPByVetfAhrwHLDAs 3.88 45477");
        events.add("ENTER CnqyhFnVBSexmjWql 1.28 6854");
        events.add("ENTER NPATRwzluaTbBGEEV 0.47 15319");
        events.add("ENTER BbIEFcctfe 2.91 47211");
        events.add("ENTER yWUuFeagdAyVDbenVbbGcY 0.04 95832");
        events.add("ENTER XwiGSOijoeuCMS 1.50 25544");
        events.add("ENTER GtcBhSJtoufxeIICVZpmmmwDz 1.16 77976");
        events.add("ENTER qiVKEgsJEcI 1.41 70440");
        events.add("ENTER RSyuJtUzOBInnDaSizANP 1.07 81596");
        events.add("ENTER RqHzRGaMN 3.83 51008");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER paQxDZezf 2.53 33475");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER xKYDAuKoYKNMOlXpBrRXIXRdy 2.73 57021");
        events.add("ENTER CJiMAnK 1.22 6466");
        events.add("SERVED");
        events.add("ENTER KYOZxSTfadhf 2.22 81004");
        events.add("ENTER wMtBhpi 0.67 5830");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER cMAJSIonRZPm 1.02 6411");
        events.add("ENTER UfodzkIUPq 1.65 61955");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER lbPfdh 3.99 40529");
        events.add("SERVED");
        events.add("ENTER TujJyAqfkNLyQvsBqDTZTtE 1.49 17756");
        events.add("ENTER oCIlaYqmtfVYmhjzSq 0.90 54327");
        events.add("ENTER donyjAYHfLr 2.43 72369");
        events.add("ENTER YYkhfU 2.40 71225");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER ElgHult 0.36 66435");
        events.add("ENTER lmtaDxMMcJM 2.75 54605");
        events.add("ENTER VbhDSfeqHipsHfCDhyBxEkwR 0.08 60541");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER AeSWltKWYJeJjTDnVcDe 0.45 31519");
        events.add("ENTER YHapUC 0.44 26945");
        events.add("ENTER ZROvjjXKY 2.47 54454");
        events.add("SERVED");
        events.add("ENTER AsybwUtIBKUKUcWgkcIdNFf 1.19 33244");
        events.add("SERVED");
        events.add("ENTER stedKTzivLGuxWiUGGiLxtiS 0.07 8342");
        events.add("ENTER hbvlEnxflCY 1.25 24170");
        events.add("SERVED");
        events.add("ENTER RoNJdTxrznB 2.75 98412");
        events.add("SERVED");
        events.add("ENTER CtzrYMJCehYKqfQeW 1.13 32545");
        events.add("ENTER nmUNI 0.51 40342");
        events.add("ENTER kwFBSPGRkwwCQCrblpzRQE 3.34 66539");
        events.add("SERVED");
        events.add("ENTER lFzVXIkJoqEbDoDuNsLVCLHF 0.80 47219");
        events.add("ENTER SOeybsLNyG 3.26 314");
        events.add("ENTER YLVssdLleRGbiBlpJmh 3.91 13696");
        events.add("ENTER CAfIPV 2.26 14658");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER ALifNKluDGwGne 2.08 94319");
        events.add("ENTER rsRhrdXIGoZcodolgpwnUl 3.23 75843");
        events.add("SERVED");
        events.add("ENTER ihfPZUPkGQgSauqXemBjWbTc 3.65 92536");
        events.add("ENTER TscDSTZnBkZUbLp 3.06 39694");
        events.add("ENTER oOpEZFuy 3.31 23564");
        events.add("SERVED");
        events.add("ENTER YaiwseMkDNaPCOOuXJegVE 1.73 85806");
        events.add("ENTER ryCYoUaXTBVQVaKdJSrZj 3.60 79256");
        events.add("ENTER RcXPYjvzXpAvZkE 0.34 24342");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER yrgCjKJ 1.30 49394");
        events.add("ENTER ybbVlvUhZkFmzAetga 3.80 85177");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER lrfmZhruRVMJCYiJsptOf 1.91 29630");
        events.add("SERVED");
        events.add("ENTER hdECBb 0.58 59162");
        events.add("ENTER shCwltKRmYfHLBvgPBPMCBwb 4.00 14730");
        events.add("SERVED");
        events.add("ENTER MtmPGRfHTl 2.02 65264");
        events.add("ENTER MMCrTnli 0.33 97741");
        events.add("SERVED");
        events.add("ENTER pqYDFCrFWHPUE 1.42 72960");
        events.add("ENTER sCRfgrHvFrNTEOV 2.49 70783");
        events.add("SERVED");
        events.add("ENTER hmRLvQAQNgMOYVfXwkd 3.22 52517");
        events.add("SERVED");
        events.add("ENTER QxLKFdb 2.11 62038");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER wqySKFXo 2.25 91574");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER LnNCjZHVxQFgRARdpizjwBgxr 0.75 89792");
        events.add("ENTER HDgYHeCQOMawCmj 1.95 13330");
        events.add("SERVED");
        events.add("ENTER mCyfGUQqvsGZUPsg 0.16 82649");
        events.add("ENTER zSvYuBvaEscBoPDTc 1.02 62953");
        events.add("ENTER fTfDGHQPKcFrrwRyD 1.77 14415");
        events.add("ENTER BwwcAKfTQyKwIbQxpgpvxrem 3.35 60727");
        events.add("SERVED");
        events.add("ENTER TATDaX 1.77 32311");
        events.add("ENTER appiUpzBdOMXoSCPvXgxkcgf 1.96 77230");
        events.add("ENTER ArBDXRSksuqeIjpMNLODl 2.10 70500");
        events.add("ENTER lXMKDs 2.51 77273");
        events.add("ENTER YGxLawMqnZQBfVCxa 2.69 49915");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER EaGYnxIXReHQyrALpsAda 3.93 38596");
        events.add("SERVED");
        events.add("ENTER BVPebJAIgDXiDZX 3.48 59643");
        events.add("SERVED");
        events.add("ENTER sAgjDBPJkZXXO 2.07 72192");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER nGicCIuxAPIMfL 0.76 76273");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER QuTOiugYXnffrsjLs 2.85 99439");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER CvnEoyynXtJzlh 3.02 33305");
        events.add("ENTER VbukivdFGPqjqWWOhcaOJPbS 2.99 74349");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER EWAKSUHNRqghvPlHD 2.28 35747");
        events.add("SERVED");
        events.add("ENTER NYTJrDc 0.64 41793");
        events.add("SERVED");
        events.add("ENTER VROaBdSrDToBVlAsZDKy 1.73 67843");
        events.add("ENTER CepAbv 3.70 15415");
        events.add("ENTER haeguJGYf 0.94 23020");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER oYSoUYjlycI 1.49 3501");
        events.add("ENTER nyLqUgTZVLmBNWi 2.83 37903");
        events.add("ENTER FWzmrWryFRj 1.71 94328");
        events.add("ENTER ZMpPmZTxNGtVzMqXrFt 1.26 42448");
        events.add("ENTER XSCRpuizmWnLxhxaBPoInHsk 0.50 84413");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER FoubkN 1.33 53666");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER XXpba 3.47 41209");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER FkobKCUgdls 2.40 24304");
        events.add("ENTER RUPfThSaykILsNguGHnERT 1.61 19570");
        events.add("SERVED");
        events.add("ENTER KTPPQElYaDEyvRKQizhwUXSPi 3.63 7686");
        events.add("ENTER khwjTmtBHLOBA 3.13 63237");
        events.add("ENTER sFNKqwRcVqMUqifGZxdtTD 1.55 99023");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER xemJbIvPQoQ 2.37 51786");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER uUsxMvvwMZbuEea 3.73 45555");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER OzUvWoOlFPhYLUJMMDeK 3.88 24821");
        events.add("SERVED");
        events.add("ENTER CLQcWsyvBplyr 3.05 39223");
        events.add("SERVED");
        events.add("ENTER TWMVdIqxjgBIgxkQWgfwO 3.66 78997");
        events.add("ENTER GXWukqtveOAKfSduQgDKcwy 3.22 98296");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER SNYuVmvBACZVF 2.93 56185");
        events.add("SERVED");
        events.add("ENTER HzoeMLrwciZqT 1.40 28569");
        events.add("ENTER GRIllHJLzK 3.21 1463");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER NGuZsyf 2.17 60254");
        events.add("ENTER DOMrXBlsCvQihIIBW 0.35 32308");
        events.add("SERVED");
        events.add("ENTER YWrQMUSnle 3.84 98409");
        events.add("ENTER utLSNWoQfuiHWTOfDkTTZRMhw 1.18 51037");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER bomCytxGHGi 0.09 97933");
        events.add("SERVED");
        events.add("ENTER tWnSdjEsxVSbZtGzgaGxfZO 1.79 48060");
        events.add("ENTER mPFczoPwjwoCeP 2.23 62179");
        events.add("ENTER mmbRRBFxaaHrZfwjRd 1.39 15519");
        events.add("ENTER xpTQlNqz 1.27 57418");
        events.add("SERVED");
        events.add("ENTER glptxHNyLdGsyMZSYlr 2.78 35163");
        events.add("ENTER VwEOAe 2.27 78203");
        events.add("SERVED");
        events.add("ENTER OIWuEdo 3.27 34376");
        events.add("ENTER DrKFicspkkSpy 0.32 22336");
        events.add("ENTER aWyFOuAWguGBKPUHoDu 0.98 83396");
        events.add("ENTER cQxevQrKs 3.07 23053");
        events.add("ENTER AJDvkuxSph 3.47 61668");
        events.add("ENTER foWEzfuwptbFkwiWwXdqfua 3.53 1889");
        events.add("ENTER LsIkkVNbdWABwIANR 3.78 20029");
        events.add("SERVED");
        events.add("ENTER zwwFQMwyzKmdM 0.77 39386");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER WAIeqXSQml 2.34 19468");
        events.add("ENTER GDwWukhV 2.54 6762");
        events.add("SERVED");
        events.add("ENTER bbITRAByzjSAIhovfOgS 3.18 6582");
        events.add("ENTER wMgxDxWlQJrYaujHKIsnWrMp 3.59 50261");
        events.add("ENTER NQZAbFSnPudOhyWuXFVsvU 0.98 42633");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER sXeapHUzIkYqmjfaMAgkcL 3.22 48647");
        events.add("SERVED");
        events.add("ENTER sfAiidXuOoxQmlK 1.15 16592");
        events.add("SERVED");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER uEOxpQNXaMkpWM 1.65 96989");
        events.add("SERVED");
        events.add("ENTER efcHhxhYfdiVJEYsRx 0.62 57306");
        events.add("ENTER iwKcOlSyvizeJ 2.55 68304");
        events.add("ENTER zyozlUCSWW 1.29 71892");
        events.add("ENTER kADHfrniomCCCAyc 3.41 96532");
        events.add("SERVED");
        events.add("SERVED");
        events.add("ENTER iBWdYCecwjzDxhCZNBAZWv 2.04 21199");
        events.add("SERVED");
        events.add("SERVED");
        
        
        List<Student> students = priorities.getStudents(events);
        
        if (students.isEmpty()) {
            System.out.println("EMPTY");
        } else {
            for (Student st: students) {
                System.out.println(st.getName());
            }
        }
    }
}